name: Docker

on:
  push:
    branches: [master]

jobs:
  build:
    name: Push
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: guni1192/internal-namespace-expoter
          tag_with_ref: true
          tag_with_sha: true
